#!/bin/bash
bin/behat --strict -f progress -s addressing
bin/behat --strict -f progress -s emails
bin/behat --strict -f progress -s orders
bin/behat --strict -f progress -s payments
bin/behat --strict -f progress -s pricing
bin/behat --strict -f progress -s settings
bin/behat --strict -f progress -s shipping
bin/behat --strict -f progress -s taxation
bin/behat --strict -f progress -s i18n
bin/behat --strict -f progress -s channels
bin/behat --strict -f progress -s products
bin/behat --strict -f progress -s promotions
